package HyperGlossary::Model::hgDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'HyperGlossary::SchemaClass',
    
    connect_info => {
        dsn => 'dbi:mysql:hg',
        user => HyperGlossary->config->{hgdb}->{user},
        password => HyperGlossary->config->{hgdb}->{pass},
    }
);

=head1 NAME

HyperGlossary::Model::hgDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<HyperGlossary>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<HyperGlossary::SchemaClass>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.30

=head1 AUTHOR

root

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
